run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam

issues:
  exclude-dirs:
    - test/e2e
